// Generated by CoffeeScript 1.9.2
(function() {
  var Promise, config, createViews, dataDb, dbDriver, dbServer, delta1, delta2, expect, updateDeltas, weight;

  expect = require('must');

  require('../../../openbeelab-util/javascript/objectUtils').install();

  require('../../../openbeelab-util/javascript/arrayUtils').install();

  config = require('../config');

  dbDriver = require('../../../openbeelab-db-util/javascript/mockDriver');

  Promise = require('promise');

  dbServer = dbDriver.connectToServer(config.services.database);

  dataDb = dbServer.useDb(config.services.database.name);

  createViews = require('../../../openbeelab-db-admin/javascript/create_views');

  updateDeltas = require('../update_deltas');

  weight = {
    type: "measure",
    name: 'global-weight',
    value: 45.6,
    timestamp: '2016-01-28T10:23:55',
    measureOrigin: "manual",
    beehouse_id: "abeehouse"
  };

  delta1 = {
    type: "measure",
    name: 'global-weight-delta',
    value: -5.6,
    timestamp: '2016-01-28T10:25:18',
    measureOrigin: "automatic",
    beehouse_id: "abeehouse"
  };

  delta2 = {
    type: "measure",
    name: 'global-weight-delta',
    value: 8.3,
    timestamp: '2016-01-28T11:45:09',
    measureOrigin: "automatic",
    beehouse_id: "abeehouse"
  };

  describe("the update delta function:", function() {
    before(function(done) {
      return dataDb.create().then(function() {
        return createViews(dataDb, "data");
      }).then(function() {
        Promise.all([dataDb.save(weight), dataDb.save(delta1), dataDb.save(delta2)]);
        return done();
      })["catch"](function(err) {
        console.log(err);
        return done(err);
      });
    });
    after(function(done) {
      dbServer.deleteDb(config.services.database.name);
      return done();
    });
    return it("should update delta, and create new absolute measure", function(done) {
      console.log(dbServer);
      return updateDeltas(dataDb, "beehouse", "abeehouse", "global-weight").then(function() {
        return dataDb.get('_design/beehouse/_view/global-weight-delta');
      }).then(function(deltas) {
        console.log("deltas == 0");
        deltas.total_rows.must.be(0);
        return dataDb.get('_design/beehouse/_view/global-weight');
      }).then(function(weights) {
        weights.total_rows.must.be(3);
        weights.rows[1].key.must.be(["beehouse", delta1.timestamp]);
        return done();
      })["catch"](function(err) {
        console.log('err: ' + err);
        return done(err);
      });
    });
  });

}).call(this);
