// Generated by CoffeeScript 1.9.2
(function() {
  var Date, Promise, config, createUsers, dataDb, dbDriver, dbServer, expect, usersDb;

  expect = require('must');

  require('../../../openbeelab-util/javascript/objectUtils').install();

  require('../../../openbeelab-util/javascript/arrayUtils').install();

  config = require('../config');

  dbDriver = require('../../../openbeelab-db-util/javascript/mockDriver');

  Promise = require('promise');

  dbServer = dbDriver.connectToServer(config.database);

  usersDb = dbServer.useDb("_users");

  dataDb = dbServer.useDb(config.database.name);

  createUsers = require('../create_users');

  Date = require('timeshift-js').Date;

  describe("an admin and an uploader for a db", function() {
    before(function(done) {
      return usersDb.create().then(done)["catch"](function(err) {
        console.log(err);
        return done(err);
      });
    });
    after(function(done) {
      dbServer.deleteDb("_users");
      return done();
    });
    return it("should be created", function(done) {
      return createUsers(usersDb, config.database.name).then(function(users) {
        var adminProm, uploaderProm;
        adminProm = usersDb.get(users.admin._id);
        uploaderProm = usersDb.get(users.uploader._id);
        return Promise.all([adminProm, uploaderProm]);
      }).then(function(arg) {
        var admin, uploader;
        admin = arg[0], uploader = arg[1];
        admin.name.must.be(config.database.name + "_admin");
        admin._id.must.be("org.couchdb.user:" + config.database.name + "_admin");
        admin.roles.must.contain(config.database.name + "/admin");
        uploader.name.must.be(config.database.name + "_uploader");
        uploader._id.must.be("org.couchdb.user:" + config.database.name + "_uploader");
        uploader.roles.must.contain(config.database.name + "/uploader");
        return done();
      })["catch"](function(err) {
        console.log('err: ' + err);
        return done(err);
      });
    });
  });

}).call(this);
