// Generated by CoffeeScript 1.9.2
(function() {
  var config, db, dbConfig;

  config = require('./config');

  dbConfig = config.services.database;

  db = require('../../openbeelab-db-util/javascript/dbUtil').database(dbConfig);

  db.get('_design/ruche2/_view/deltas').then(function(result) {
    var delta, deltas, i, len, results;
    deltas = result.rows.map(function(row) {
      return row.value;
    });
    results = [];
    for (i = 0, len = deltas.length; i < len; i++) {
      delta = deltas[i];
      results.push((function(delta) {
        console.log(delta.timestamp);
        console.log(delta.beehouse_id);
        console.log(delta.value);
        delete delta.absolute_weight_inserted;
        return db.save(delta);
      })(delta));
    }
    return results;
  })["catch"](function(err) {
    return console.log(err);
  });

}).call(this);
