// Generated by CoffeeScript 1.9.2
(function() {
  var mailerConfig, nodemailer, smtpTransport;

  nodemailer = require('nodemailer');

  smtpTransport = require('nodemailer-smtp-transport');

  mailerConfig = require('./config').services.mailer;

  module.exports = nodemailer.createTransport(smtpTransport(mailerConfig));

}).call(this);
