// Generated by CoffeeScript 1.9.2
(function() {
  var Promise, config, db, dbConfig, moment;

  moment = require('moment');

  Promise = require('promise');

  config = require('./config');

  dbConfig = config.services.database;

  db = require('../../openbeelab-db-util/javascript/dbDriver').connectToServer(dbConfig.database).useDb(config.database.name + "_config");

  db.exists().then(function(exists) {
    if (!exists) {
      Promise.reject("db doesnt exist");
    }
    return exists;
  }).then(function(exists) {
    return db.get('_design/apiaries/_view/by_name').then(function(apiaries) {
      var apiary, i, len, results;
      results = [];
      for (i = 0, len = apiaries.length; i < len; i++) {
        apiary = apiaries[i];
        results.push((function(apiary) {
          var beehouse_id, j, len1, ref, results1;
          apiary = apiary.value;
          if (apiary.beehouses != null) {
            ref = apiary.beehouses;
            results1 = [];
            for (j = 0, len1 = ref.length; j < len1; j++) {
              beehouse_id = ref[j];
              results1.push((function(beehouse_id) {
                return db.get(beehouse_id).then(function(beehouse) {
                  var lastMeasureUrl;
                  if (beehouse != null ? beehouse.isActive : void 0) {
                    lastMeasureUrl = '_design/' + beehouse.name + '/_view/weight?descending=true&limit=1';
                    return db.get(lastMeasureUrl).then(function(lastMeasure) {
                      var alertTime, beekeeper_id, k, lastMeasureTime, len2, now, ref1, results2, trigger;
                      if (lastMeasure != null) {
                        lastMeasure = lastMeasure.rows[0].value;
                        now = moment(new Date());
                        lastMeasureTime = moment(new Date(lastMeasure.timestamp));
                        trigger = config.alerts.connectionTrigger;
                        alertTime = lastMeasureTime.add(trigger.value, trigger.unit);
                        if (now.isAfter(alertTime)) {
                          if ((apiary.beekeepers != null) && apiary.beekeepers.length > 0) {
                            ref1 = apiary.beekeepers;
                            results2 = [];
                            for (k = 0, len2 = ref1.length; k < len2; k++) {
                              beekeeper_id = ref1[k];
                              results2.push((function(beekeeper_id) {
                                return db.get(beekeeper_id).then(function(beekeeper) {
                                  var diff, mailOptions, mailer;
                                  mailer = require('./mailTransporter');
                                  diff = now.diff(lastMeasureTime, 'minutes');
                                  mailOptions = {
                                    from: 'openbeelab beehouse monitoring ✔ <remy.openbeelab@gmail.com>',
                                    to: beekeeper.email,
                                    subject: 'beehouse disconnected',
                                    text: 'beehouse ' + beehouse.name + ' from apiary ' + apiary.name + ' didn\'t send data since ' + diff + ' minutes.'
                                  };
                                  return mailer.sendMail(mailOptions, function(error, info) {
                                    if (error) {
                                      return console.log(error);
                                    } else {
                                      return console.log('Message sent: ' + info.response);
                                    }
                                  });
                                });
                              })(beekeeper_id));
                            }
                            return results2;
                          }
                        }
                      }
                    });
                  }
                });
              })(beehouse_id));
            }
            return results1;
          }
        })(apiary));
      }
      return results;
    });
  })["catch"](function(err) {
    var admin, i, len, ref, results;
    ref = config.admins;
    results = [];
    for (i = 0, len = ref.length; i < len; i++) {
      admin = ref[i];
      results.push((function(admin) {
        var mailOptions, mailer;
        mailer = require('./mailTransporter');
        mailOptions = {
          from: 'openbeelab beehouse monitoring ✔ <remy.openbeelab@gmail.com>',
          to: admin.email,
          subject: 'db down',
          text: 'openbeelab db seems to be down...'
        };
        return mailer.sendMail(mailOptions, function(error, info) {
          if (error) {
            return console.log(error);
          } else {
            return console.log('Message sent: ' + info.response);
          }
        });
      })(admin));
    }
    return results;
  });

}).call(this);
